# Muestra tu perfil de GitHub Sponsors
github: rcdrodrigo

# Muestra un enlace a Ko-fi
ko_fi: tu_usuario_de_kofi

# Muestra un enlace a Buy Me a Coffee
buy_me_a_coffee: tu_usuario_de_buymeacoffee

# También puedes agregar otras plataformas como Patreon
# patreon: tu_usuario_de_patreon

# O incluso enlaces personalizados si tu plataforma no está en la lista
# custom: ['https://www.paypal.me/tu_usuario_paypal']
